language: java
sudo: false
services:
- postgresql
before_script:
- psql -c "CREATE DATABASE public;" -U postgres
#   - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres
script:
- mvn clean validate compile verify
before_install:
- openssl aes-256-cbc -K $encrypted_6ce9b8886f1a_key -iv $encrypted_6ce9b8886f1a_iv
  -in ada-creds.json.enc -out ada-creds.json -d
- export GOOGLE_APPLICATION_CREDENTIALS=$PWD/ada-creds.json
- export AUDIODEV=null
